config/routes.rb
Rails.application.routes.draw do
  resources :suggested_cars
  root 'cars#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  resources :cars do
    resources :reservations
  end
  resources :suggested_cars
  get 'reservation_history', to: 'users#reservation_history'
  get 'cars/:id/subscriptions/new_subscription', to: 'subscriptions#new_sbscription', as: 'new_subscription'
  namespace :admin do
    root 'admin/cars#index'
    resources :users do
      resources :reservations, only: [:new, :create]
    end
    get 'customers', to: 'users#customers'
    resources :cars
    get 'cars/:id/edit_status', to: 'cars#edit_status', as: 'car_edit_status'
    get 'suggested_cars/:id/cars/new_suggested_car', to: 'cars#new_suggested_car', as: 'new_suggested_car'
    post 'suggested_cars/:id/cars/create_suggested_car', to: 'cars#create_suggested_car', as: 'create_suggested_car'
    patch 'cars/:id/update_status', to: 'cars#update_status', as: 'car_update_status'
    get 'cars/:id/reservation_history', to: 'cars#reservation_history', as: 'car_reservation_history'
    get 'users/:id/reservation_history', to: 'users#reservation_history', as: 'user_reservation_history'
    resources :reservations
  end
  namespace :super_admin do
    root 'admin/cars#index'
    resources :users
  end
end

app/models/car.rb
class Car < ApplicationRecord
  enum status: { available: 'Available', reserved: 'Reserved', checked_out: 'Checked out', inactive: 'Inactive'}
  enum style: { coupe: 'Coupe', sedan: 'Sedan', suv: 'SUV' }
  has_many :reservations
  has_many :users, through: :reservations

  validates :licence_no, :manufacturer, :model, :style, :hourly_rate, :location, :status, presence: true
  validates :licence_no, length: { is: 7 }
  validates :licence_no, uniqueness: true
  validates :hourly_rate, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < Admin::AdminController
  include ApplicationHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy, :reservation_history, :edit_status, :update_status]
  before_action :set_suggested_car, only: [:new_suggested_car, :create_suggested_car]
  # GET admin/cars
  # GET admin/cars.json
  def index
    @cars = Car.where.not(:status => :inactive).paginate(:page => params[:page], :per_page => 8)
  end

  # GET admin/cars/1
  # GET admin/cars/1.json
  def show
  end

  # GET admin/cars/1/reservation_history
  # GET admin/cars/1/reservation_history.json
  def reservation_history
    @reservations = @car.reservations
  end

  # GET admin/cars/new
  def new
    @car = Car.new
    puts "In desired method."
  end

  # GET admin/cars/1/edit
  def edit
  end

  # POST astatusdmin/cars
  # POST admin/cars.json
  def create
    @car = Car.new(car_params)
    @car.status = "available"
    respond_to do |format|
      if @car.save
        format.html { redirect_to admin_cars_path, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_suggested_car
    @car = Car.new
    @car.manufacturer = @suggested_car.manufacturer
    @car.model = @suggested_car.model
    @car.style = @suggested_car.style
    @car.location = @suggested_car.location
  end

  def create_suggested_car
    @car = Car.new(car_params)
    @car.status = "available"
    @suggested_car_status = "accepted"
    respond_to do |format|
      if @car.save and @suggested_car.update(:status => @suggested_car_status)
        format.html { redirect_to admin_cars_path, notice: 'Suggested Car was successfully accepted and added into the system.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT admin/cars/1
  # PATCH/PUT admin/cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to admin_cars_path, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET admin/cars/1/edit_status
  def edit_status
  end

  # PATCH/PUT admin/cars/1/update_status
  def update_status
    @reservation = @car.reservations.where(:status => 'Current').first
    respond_to do |format|
      if @car.reserved?
        car_status = :checked_out
        reservation_status = 'current'
        message = 'Car was successfully checked out.'
      else
        car_status = :available
        reservation_status = 'past'
        message = 'Car was successfully returned.'
      end
      if @car.update(:status => car_status) and @reservation.update(:status => reservation_status)
        if reservation_status == 'past'
          send_notification(@car)
        end
        format.html { redirect_to admin_customers_path, notice: message }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit_status, alert: 'Something went wrong!!' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE admin/cars/1
  # DELETE admin/cars/1.json
  def destroy
    return redirect_to admin_cars_path, notice: 'Car is still in use, It cannot be deleted now' unless @car.available?
    if @car.reservations
      @car.update(status: :inactive)
      respond_to do |format|
        format.html { redirect_to admin_cars_path, notice: 'Car was successfully marked as inactive.' }
        format.json { head :no_content }
      end
    else
      @car.destroy
      respond_to do |format|
        format.html { redirect_to admin_cars_path, notice: 'Car was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_suggested_car
      @suggested_car = SuggestedCar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:licence_no, :manufacturer, :model, :style, :hourly_rate, :location, :status)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include ApplicationHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :set_current_car, only: [:edit, :update]
  before_action :set_user, only: [:show, :index]

  # GET /cars
  # GET /cars.json
  def index
    if !params[:query]
      @cars = Car.where.not(:status => :inactive).paginate(:page => params[:page], :per_page => 6)
    else
      @cars = Car.where("#{params[:status].to_sym} ilike ?", "%#{params[:query].to_s}%").paginate(:page => params[:page], :per_page => 6)
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @current_car.reserved?
        @car_status = "checked_out"
        @reservation_status = "current"
        @message = 'Car was successfully checked out.'
      else
        @car_status = "available"
        @reservation_status = "past"
        @message = 'Car was successfully returned.'
      end
      if @current_car.update(:status => @car_status) and @reservation.update(:status => @reservation_status)
        if @reservation_status == 'past'
          send_notification(@car)
        end
        format.html { redirect_to root_path, notice: @message }
        format.json { render :show, status: :ok, location: @current_car }
      else
        format.html { render :edit }
        format.json { render json: @current_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def set_current_car
      @reservation = user_reservation
      @current_car = Car.find(@reservation.car_id)
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:licence_no, :manufacturer, :model, :style, :hourly_rate, :location, :status)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_edit_form.html.erb
<%= form_for(@car) do |form| %>
  <% if @car.reserved? %>
        <div class="actions">
          <%= form.submit 'Check Out', class: 'btn-submit' %>
        </div>
  <% end %>
  <% if @car.checked_out? %>
        <div class="actions">
          <%= form.submit 'Return', class: 'btn-submit' %>
        </div>
  <% end %>
<% end %>

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
    <% if car.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% car.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :licence_no %>
      <%= form.text_field :licence_no, id: :car_licence_no %>
    </div>

    <div class="field">
      <%= form.label :manufacturer %>
      <%= form.text_field :manufacturer, id: :car_manufacturer, :placeholder => @car.manufacturer  %>
    </div>

    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model, id: :car_model %>
    </div>

    <div class="field">
      <%= form.label :style %>
      <%= form.select :style, Car.styles.values, id: :car_style %>
    </div>

    <div class="field">
      <%= form.label :hourly_rate %>
      <%= form.text_field :hourly_rate, id: :car_hourly_rate %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location, id: :car_location %>
    </div>

    <div class="actions">
      <%= form.submit form_for == :cars ? 'Add' : 'Save', class: 'btn-submit' %>
    </div>

<% end %>

app/views/cars/_search_form.html.erb
<%= form_with(local: true, method: 'get') do |form| %>
    <%= form.text_field :query, id: :car_query, :placeholder => 'Search' %>
    <%= form.select :status, Car.attribute_names.select { |x|  x.in?(["manufacturer","style","status","location","model"])  }, id: :car_attr %>
    <%= form.button 'Search', class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-search"></span>
    <% end %>
<% end %>

app/views/cars/edit.html.erb
<% if @current_car.reserved? %>
    <p>Checking out the following car.</p>
<% end %>
<% if @current_car.checked_out? %>
    <p>Returning the following car.</p>
<% end %>

<p>
  <strong>Licence no:</strong>
  <%= @current_car.licence_no %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @current_car.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @current_car.model %>
</p>

<p>
  <strong>Style:</strong>
  <%= @current_car.style %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @current_car.hourly_rate %>
</p>

<p>
  <strong>Location:</strong>
  <%= @current_car.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @current_car.status.humanize %>
</p>

<%= render 'edit_form', car: @current_car, form_for: :edit %>

app/views/cars/index.html.erb
<div class="search">
  <br>
  <h4>Current Reservation</h4>
  <% if @reservation = user_reservation %>
      <% @current_car = Car.find(@reservation.car_id)%>
      <table class="table">
        <thead>
        <tr>
          <th>Licence no</th>
          <th>Manufacturer</th>
          <th>Model</th>
          <th>Style</th>
          <th>From</th>
          <th>To</th>
          <th>Rental Charge</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @current_car.licence_no %></td>
            <td><%= @current_car.manufacturer %></td>
            <td><%= @current_car.model %></td>
            <td><%= @current_car.style.humanize %></td>
            <td><%= @reservation.from %></td>
            <td><%= @reservation.to %></td>
            <td><%= @reservation.rental_charge %></td>
            <% if @current_car.reserved?%>
                <% if @reservation.valid_time_to_check_out? %>
                  <td><%= link_to 'Check out car', edit_car_path(@current_car) %></td>
                <% end %>
                <td><%= link_to 'Cancel Reservation', car_reservation_path(@current_car,@reservation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
            <% if @current_car.checked_out? %>
                <td><%= link_to 'Return car', edit_car_path(@current_car) %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <% if @current_car.reserved? and !@reservation.valid_time_to_check_out? %>
          <h5 style="text-indent: 35px">Checkout link will be available before 10 minutes of your reservation. &nbsp;&nbsp;&nbsp; <%= link_to "Reload", root_path %></h5>
      <% end %>
  <% else %>
      <h5 style="text-indent: 35px">You don't have any current reservation.</h5>
  <% end %>
  <br>
  <h4>Reservation History</h4>
    <h5 style="text-indent: 35px"><%= link_to 'View History', reservation_history_path %></h5>
  <br>
  <%= render 'search_form' %>
  <table class="table">
    <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Style</th>
      <th>Hourly rate</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @cars.each do |car| %>
        <tr>
          <td><%= car.manufacturer %></td>
          <td><%= car.model %></td>
          <td><%= car.style.humanize %></td>
          <td><%= car.hourly_rate %></td>
          <td><%= car.location %></td>
          <td><%= car.status.humanize %></td>
          <td><%= link_to 'Details', car %></td>
          <% if car.available? and !user_reservation %>
              <td><%= link_to 'Rent This Car', new_car_reservation_path(car) %></td>
          <% end %>
          <% if !car.available? and !checked_out_by_current_user?(car) and !user_subscription(car)  %>
              <td><%= link_to 'Notify when available', new_subscription_path(car.id) %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate @cars %>

  <h5>Did not like our collection of Cars? Suggest a Car to us.</h5>
  <h5><%= link_to 'Suggest a Car', new_suggested_car_path %></h5>
</div>

app/views/cars/new.html.erb
<h3>New Car</h3>

<%= render 'form', car: @car, form_for: :cars %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p>
  <strong>Licence no:</strong>
  <%= @car.licence_no %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Style:</strong>
  <%= @car.style.humanize %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @car.hourly_rate %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status.humanize %>
</p>

<% if @car.available? and !user_reservation %>
  <%= link_to 'Rent This Car', new_car_reservation_path(@car) %> |
<% end %>
<%= link_to 'Back', root_path %>