config/routes.rb
Rails.application.routes.draw do
  resources :suggested_cars
  root 'cars#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  resources :cars do
    resources :reservations
  end
  resources :suggested_cars
  get 'reservation_history', to: 'users#reservation_history'
  get 'cars/:id/subscriptions/new_subscription', to: 'subscriptions#new_sbscription', as: 'new_subscription'
  namespace :admin do
    root 'admin/cars#index'
    resources :users do
      resources :reservations, only: [:new, :create]
    end
    get 'customers', to: 'users#customers'
    resources :cars
    get 'cars/:id/edit_status', to: 'cars#edit_status', as: 'car_edit_status'
    get 'suggested_cars/:id/cars/new_suggested_car', to: 'cars#new_suggested_car', as: 'new_suggested_car'
    post 'suggested_cars/:id/cars/create_suggested_car', to: 'cars#create_suggested_car', as: 'create_suggested_car'
    patch 'cars/:id/update_status', to: 'cars#update_status', as: 'car_update_status'
    get 'cars/:id/reservation_history', to: 'cars#reservation_history', as: 'car_reservation_history'
    get 'users/:id/reservation_history', to: 'users#reservation_history', as: 'user_reservation_history'
    resources :reservations
  end
  namespace :super_admin do
    root 'admin/cars#index'
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :cars, through: :reservations
  belongs_to :role
  validates :email, :first_name, :last_name, :role_id, presence: true
  validates :email, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, :if => :password # only validate if password changed!


  def admin?
    role.name == 'Admin'
  end

  def super_admin?
    role.name == 'SuperAdmin'
  end

  def customer?
    role.name == 'Customer'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :reservation_history, :reserve_car]

  # GET admin/users
  # GET admin/users.json
  def index
    role = Role.find_by_name('Admin')
    @users = role.users
  end

  # GET admin/customers
  def customers
    role = Role.find_by_name('Customer')
    @users = role.users
  end

  def reservation_history
    @current_reservation = @user.reservations.where(:status => "Current").first
    @reservations = @user.reservations.where(:status => "Past")
  end

  # GET admin/users/1
  # GET admin/users/1.json
  def show
  end

  # GET admin/users/new
  def new
    @user = User.new
  end

  # GET admin/users/1/edit
  def edit
  end

  # POST admin/users
  # POST admin/users.json
  def create
    @user = User.new(user_params)
    unless @user.role
      @user.role = Role.find_by_name('Admin')
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT admin/users/1
  # PATCH/PUT admin/users/1.json
  def update
    respond_to do |format|
      if @user.customer? and @user.update(user_params_update)
        format.html { redirect_to admin_customers_path, notice: 'The user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE admin/users/1
  # DELETE admin/users/1.json
  def destroy
    if @user == current_user or @user.super_admin?
      return redirect_to admin_cars_url, alert: 'Cannot delete this user'
    end
    unless @user.reservations.empty?
      return redirect_to admin_cars_url, alert: 'Cannot delete this user!! There are reservations done by this user in the system'
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_cars_url, notice: 'The user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      redirect_to admin_users_path, alert: 'You are Unauthorized to access that page' if @user.super_admin?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :role_id)
    end
	
	def user_params_update
      params.require(:user).permit(:email, :first_name, :last_name)
    end
end

app/controllers/super_admin/users_controller.rb
class SuperAdmin::UsersController < SuperAdmin::SuperAdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET super_admin/users
  # GET super_admin/users.json
  def index
    role = Role.find_by_name('SuperAdmin')
    @users = role.users
  end

  # GET super_admin/users/1
  # GET super_admin/users/1.json
  def show
  end

  # GET super_admin/users/new
  def new
    @user = User.new
  end

  # GET super_admin/users/1/edit
  def edit
  end

  # POST super_admin/users
  # POST super_admin/users.json
  def create
    @user = User.new(user_params)
    unless @user.role
      @user.role = Role.find_by_name('SuperAdmin')
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to super_admin_users_path, notice: 'Super Admin was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT super_admin/users/1
  # PATCH/PUT super_admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to super_admin_users_path, notice: 'Super Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE super_admin/users/1
  # DELETE super_admin/users/1.json
  def destroy
    if @user == current_user or @user.super_admin?
      return redirect_to super_admin_users_path, alert: 'Super Admins cannot be deleted'
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to super_admin_users_path, notice: 'Super Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :role_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :not_logged_in, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :reservation_history]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def reservation_history
    @current_reservation = user_reservation
    @reservations = @user.reservations.where(:status => "Past")
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    unless @user.role
      @user.role = Role.find_by_name('Customer')
    end

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'Welcome to Car Rental Application.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :role_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_edit_form.html.erb
<%= form_for [:admin, @user] do |form| %>

  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, :placeholder => 'Email', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name, :placeholder => 'First Name', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name, :placeholder => 'Last Name', class: 'form-control' %>
  </div>

    <div class="actions">
    <%= form.submit class: 'btn-submit' %>
  </div>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |form| %>

  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, :placeholder => 'Email', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name, :placeholder => 'First Name', class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name, :placeholder => 'Last Name', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn-submit' %>
  </div>
<% end %>

app/views/admin/users/_users_list.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'View Details', admin_user_path(user) %></td>
        <% if user.customer? %>
            <td><%= link_to 'Reservations', admin_user_reservation_history_path(user) %></td>
            <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <% end %>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/admin/users/customers.html.erb
<h1>Customers</h1>

<%= render 'users_list' %>

app/views/admin/users/edit.html.erb
<h1>Editing <%= @user.role.name %></h1>

<%= render 'edit_form', user: [:admin, @user] %>

<%= link_to 'Back', admin_customers_path %>

app/views/admin/users/index.html.erb
<h1>Admins List</h1>

<%= render 'users_list' %>

<%= link_to 'New Admin', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New Admin</h1>

<%= render 'form', user: [:admin, @user] %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/reservation_history.html.erb
<br>
<h4>Current Reservation</h4>
<% if @current_reservation %>
  <table class="table">
    <thead>
    <tr>
      <th>Licence no</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>From</th>
      <th>To</th>
      <th>Rental Charge</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @current_reservation.car.licence_no %></td>
      <td><%= @current_reservation.car.manufacturer %></td>
      <td><%= @current_reservation.car.model %></td>
      <td><%= @current_reservation.from %></td>
      <td><%= @current_reservation.to %></td>
      <td><%= @current_reservation.rental_charge %></td>
      <% if @current_reservation.car.reserved? %>
          <% if @current_reservation.valid_time_to_check_out? %>
              <td><%= link_to 'Check out car', admin_car_edit_status_path(@current_reservation.car) %></td>
          <% end %>
          <td><%= link_to 'Cancel Reservation', admin_reservation_path(@current_reservation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <% if @current_reservation.car.checked_out? %>
          <td><%= link_to 'Return car', admin_car_edit_status_path(@current_reservation.car) %></td>
      <% end %>
    </tr>
    </tbody>
  </table>
  <% if @current_reservation.car.reserved? and !@current_reservation.valid_time_to_check_out? %>
      <h5 style="text-indent: 35px">Checkout link will be available before 10 minutes of your reservation.</h5>
  <% end %>
<% else %>
  <h5 style="text-indent: 35px">The user does not have any current reservation.</h5>
  <%= link_to 'Create reservation', new_admin_user_reservation_path(@user) %>
<% end %>
<h4>Reservation History</h4>
<% if @reservations %>
  <table class="table">
    <thead>
    <tr>
      <th>Licence no</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>From</th>
      <th>To</th>
      <th>Rental Charge</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @reservations.each do |reservation| %>
        <tr>
          <td><%= reservation.car.licence_no %></td>
          <td><%= reservation.car.manufacturer %></td>
          <td><%= reservation.car.model %></td>
          <td><%= reservation.from %></td>
          <td><%= reservation.to %></td>
          <td><%= reservation.rental_charge %></td>
          <td><%= link_to 'Show Details', admin_reservation_path(reservation) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
    <h5 style="text-indent: 35px">The user does not have a reservation history.</h5>
<% end %>
<br>
<%= link_to 'Back', admin_customers_path %>

app/views/admin/users/show.html.erb
<h2><%= @user.role.name %></h2>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>


<% if @user.customer? %>
    <%= link_to 'Reservation History', admin_user_reservation_history_path(@user) %> |
    <%= link_to 'Edit', edit_admin_user_path(@user) %>
    <br><br>
    <%= link_to 'Back', admin_customers_path %>
<% end %>
<% if @user.admin? %>
<%= link_to 'Back', admin_users_path %>
<% end %>