config/routes.rb
Rails.application.routes.draw do
  resources :suggested_cars
  root 'cars#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users
  resources :cars do
    resources :reservations
  end
  resources :suggested_cars
  get 'reservation_history', to: 'users#reservation_history'
  get 'cars/:id/subscriptions/new_subscription', to: 'subscriptions#new_sbscription', as: 'new_subscription'
  namespace :admin do
    root 'admin/cars#index'
    resources :users do
      resources :reservations, only: [:new, :create]
    end
    get 'customers', to: 'users#customers'
    resources :cars
    get 'cars/:id/edit_status', to: 'cars#edit_status', as: 'car_edit_status'
    get 'suggested_cars/:id/cars/new_suggested_car', to: 'cars#new_suggested_car', as: 'new_suggested_car'
    post 'suggested_cars/:id/cars/create_suggested_car', to: 'cars#create_suggested_car', as: 'create_suggested_car'
    patch 'cars/:id/update_status', to: 'cars#update_status', as: 'car_update_status'
    get 'cars/:id/reservation_history', to: 'cars#reservation_history', as: 'car_reservation_history'
    get 'users/:id/reservation_history', to: 'users#reservation_history', as: 'user_reservation_history'
    resources :reservations
  end
  namespace :super_admin do
    root 'admin/cars#index'
    resources :users
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if logged_in? and @current_user.customer? %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% else %>
          <% if logged_in? %>
            <%= link_to 'Home', admin_cars_path, class: 'navbar-brand' %>
          <% end %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav" style="float: right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if logged_in?%>
    <% if current_user.admin?%>
        <li><%= link_to 'Cars', admin_cars_path %></li>
        <li><%= link_to 'Reservations', admin_reservations_path %></li>
        <li><%= link_to 'Customers', admin_customers_path %></li>
        <li><%= link_to 'Admins', admin_users_path %></li>
    <% elsif current_user.super_admin?%>
        <li><%= link_to 'Cars', admin_cars_path %></li>
        <li><%= link_to 'Reservations', admin_reservations_path %></li>
        <li><%= link_to 'Customers', admin_customers_path %></li>
        <li><%= link_to 'Admins', admin_users_path %></li>
        <li><%= link_to 'SuperAdmins', super_admin_users_path %></li>
    <% end %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'My Profile', current_user%></li>
        <li>
          <%= link_to 'Edit profile', edit_user_path(current_user) %>
        </li>
        <li class="divider"></li>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      </ul>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Car Rental' %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Car Rental' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <% if logged_in? and (current_page?(root_url) or current_page?(admin_cars_url)) %>
       <h3>Hello <%= current_user.first_name %> <%= current_user.last_name %></h3>
      <% end %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>